<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DIGAMBAR-PC" name="com.qa.tests.LoginPageTest" tests="4" failures="1" timestamp="24 Jul 2018 18:04:41 GMT" time="110.349" errors="0">
  <testcase name="verifyLoginPageTitle" time="15.273" classname="com.qa.tests.LoginPageTest"/>
  <testcase name="verifyLogo" time="37.512" classname="com.qa.tests.LoginPageTest"/>
  <testcase name="verifyFooter" time="15.198" classname="com.qa.tests.LoginPageTest"/>
  <testcase name="verifyLogin" time="42.366" classname="com.qa.tests.LoginPageTest">
    <failure type="java.lang.AssertionError" message="expected [Home : Ultimatix - Digitally Connected !] but found [UltimatixHome]">
      <![CDATA[java.lang.AssertionError: expected [Home : Ultimatix - Digitally Connected !] but found [UltimatixHome]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.qa.tests.LoginPageTest.verifyLogin(LoginPageTest.java:46)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- verifyLogin -->
</testsuite> <!-- com.qa.tests.LoginPageTest -->
